### Test route
GET http://localhost:5050/hello


# JOB
### Pôle Emploi API jobs
POST  http://localhost:5050/jobs/pe

### Find all jobs
GET http://localhost:5050/jobs

### Add one job
POST http://localhost:5050/jobs/save
Content-Type: application/json
authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJFbWFpbCI6ImZlbGFuYUBvY2xvY2suaW8iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mjc1NjgwMjUsImV4cCI6MTYyNzY1NDQyNX0.pMJO0LTnblp-VoFsGxPejGRZcH9t8OjO-KKyTY4iRJQ

{
     "title": "Developpeur React junior",
     "description" : "Opportunité de folie",
     "company" : "ME",
     "technology" : "React Redux",
     "locality" : "Vernon",
     "contract" : "alternance",
     "salary" : "avec prime",
     "user_id" : 3
}

### Update one job
PATCH http://localhost:5050/jobs/update/3
Content-Type: application/json
authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJFbWFpbCI6ImZlbGFuYUBvY2xvY2suaW8iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mjc1NzAyNDcsImV4cCI6MTYyNzY1NjY0N30.9ySpQpKj8lQLwknKW3kJY8IGiOJsZQ5R3qSxt53cdNA

{
     "id": 3,
     "title": "React junior",
     "description" : "café à volonté",
     "company" : "ME",
     "technology" : "React en folie",
     "locality" : "Vernon",
     "contract" : "alternance",
     "salary" : " beaucoup",
     "user_id" : 3
}

### Find one job and delete
DELETE http://localhost:5050/jobs/delete/4
authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJFbWFpbCI6ImZlbGFuYUBvY2xvY2suaW8iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mjc1NzAyNDcsImV4cCI6MTYyNzY1NjY0N30.9ySpQpKj8lQLwknKW3kJY8IGiOJsZQ5R3qSxt53cdNA

# USER
### Find all users
GET http://localhost:5050/users

### Find one user by id
GET http://localhost:5050/user/4

### Update one user 
PATCH http://localhost:5050/users/update
Content-Type: application/json

{
     "id": 7,
     "firstName": "François",
     "lastName": "BB",
     "email": "flo@oclock.io",
     "password": "trucDeFloBB",
     "role": "Admin"
}

### Add one user/ user register
POST http://localhost:5050/users/registerUser
Content-Type: application/json

{
     "firstname": "Salade",
     "lastname": "De Fruit",
     "email": "salade@oclock.io",
     "password": "Salade"
     
}

### Find one job and delete
DELETE http://localhost:5050/user/delete/10


### Login user
POST  http://localhost:5050/user/loginUser
Content-type: application/json

{    
     "email": "felana@oclock.io",
     "password": "Felana"
}



### Add one user/ user register
POST http://localhost:5050/user/registerAdmin
Content-Type: application/json

{
     "firstName": "Michel",
     "lastName": "Drucker",
     "email": "md@oclock.io",
     "password": "michel.drucker",
     "role": "admin"
}
