### Path for  test
GET http://localhost:5050/hello

### Find all jobs
GET http://localhost:5050/jobs

### Find one job
GET http://localhost:5050/job/4

### Add one job
POST http://localhost:5050/jobs/save
Content-Type: application/json

{
     "title": "Offre2 en télétravail",
     "description" : "Pleines de trucs choses",
     "company" : "TIKO",
     "technology" : "React-Redux bien sûr",
     "locality" : "Nouvelle-Aquitaine",
     "title": "React Junior",
     "description" : "Lorem Ipsum",
     "company" : "Dom Einhorn",
     "technology" : "React bien sûr",
     "locality" : "Var",
     "contract" : "CDI",
     "salary" : "avec primes",
     "user_id" : 1
}

### Update one job
PATCH http://localhost:5050/jobs/update
Content-Type: application/json

{
     "id": 8,
     "title": "Poste React Junior",
     "description" : "Café à volonté",
     "company" : "Dom Einhorn",
     "technology" : "React et peut-être du PHP",
     "locality" : "Cher",
     "contract" : "stage",
     "salary" : "3 oeufs et une pomme",
     "user_id" : 1



}





### Find one job and delete
DELETE http://localhost:5050/job/delete/13

### Find all users
GET http://localhost:5050/users


### Find one user by id
GET http://localhost:5050/user/1
